name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Build (amd64)
      run: GOARCH=amd64 go build -v ./...

    - name: Build (386)
      run: GOARCH=386 go build -v ./...

    - name: Build (arm64)
      run: GOARCH=arm64 go build -v ./...

    - name: Build (arm)
      run: GOARCH=arm go build -v ./...
  
    - name: Test
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: petenewcomb/atomic128-go
